feat: database reader file and cron service
gravitee-io/gravitee-service-geoip pull request #7
Opened 2021-11-11 17:40 UTC by remisultan

This is a draft for: https://github.com/gravitee-io/issues/issues/6227

Right now the service reads a filename and updates it with a cron based scheduler.

Also the cache is set with an FIFO eviction policy with a cache sise

2021-12-06 10:12 UTC, remisultan commented on src/main/java/io/gravitee/service/geoip/configuration/GeoIPServiceConfiguration.java
> +    private Integer cityCacheCapacity;
using `${geoip.database.city.filename:#{null}` did not work for me, the Values were not injected properly.
@tcompiegne @leleueri

2021-12-10 13:24 UTC, leleueri requested changes

2021-12-10 13:24 UTC, leleueri commented on src/main/java/io/gravitee/service/geoip/configuration/GeoIPServiceConfiguration.java
> +    private Integer cityCacheCapacity;
Did you try with :  
```
    @Value("${geoip.database.city.filename:#{null}}")
    private String filename;

    @Value("${geoip.database.city.watch:false}")
    private boolean watch;

    @Value("${geoip.database.city.cache.capacity:4096}")
    private int cityCacheCapacity;
```

With the current impl, environment variables are not managed

2021-12-10 13:24 UTC, leleueri commented on src/main/java/io/gravitee/service/geoip/service/DatabaseReaderWatcherService.java
> +        optionalReader.ifPresentOrElse(
If after a file update, a new version of the file can't be read then we will fallback to the embedded version instead of using the already loaded instance that should be more up to date than the embedded one. 

Do we have to check if an instance already exist before fallback to the embedded one?

2021-12-10 14:20 UTC, remisultan commented on src/main/java/io/gravitee/service/geoip/service/DatabaseReaderWatcherService.java
> +        optionalReader.ifPresentOrElse(
@leleueri  yes we have to. Because the previous instance might be working and we don't want to fallback to the embedded one which is outdated

2021-12-10 14:25 UTC, remisultan commented on pom.xml
> +            <groupId>org.cache2k</groupId>
I did not want to include all guava since Cache2k is lightweight ? Is `guava` included in the context of the gateway (or the `bom`) ? 
Otherwise I can just label it with a `provided` and implement guava

2021-12-10 14:27 UTC, remisultan commented on src/main/java/io/gravitee/service/geoip/service/DatabaseReaderWatcherService.java
> +            var oldReader = databaseReaderService.get(cityDbType);
Not in the case where the pathname is null and that the embeddedDb is corrupted.
This is more of security than anything

2021-12-10 14:34 UTC, remisultan commented on src/main/java/io/gravitee/service/geoip/configuration/GeoIPServiceConfiguration.java
> +    private Integer cityCacheCapacity;
Will try once again

2021-12-12 22:10 UTC, remisultan commented on pom.xml
> +            <groupId>org.cache2k</groupId>
Done

2021-12-12 22:10 UTC, remisultan commented on src/main/java/io/gravitee/service/geoip/configuration/GeoIPServiceConfiguration.java
> +    private Integer cityCacheCapacity;
Done and it worked

2021-12-12 22:12 UTC, remisultan commented on pom.xml
> +            <groupId>org.cache2k</groupId>
https://github.com/gravitee-io/gravitee-access-management/pull/1449/files
Had to update guava in am parent pom so it matched apim version

2021-12-13 19:49 UTC, leleueri approved these changes

2021-12-13 19:49 UTC, merged